// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtugwhcakgciauvwnngx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0dWd3aGNha2djaWF1dndubmd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MjY3OTYsImV4cCI6MjA3MTQwMjc5Nn0.-JDxmLwmxBt-qTr6oMb53MItLf_qBrQLhO06toudIL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});